events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 7860;
        server_name localhost;

        root /var/www/public;
        index index.php index.html;

        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # TAMBAHKAN BLOK INI: Khusus menangani file gambar/statis di folder storage
        location /storage/ {
            alias /var/www/storage/app/public/;
            try_files $uri =404;
            access_log off;
            log_not_found off;
            expires max;
        }

        error_page 404 /index.php;

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}