events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 7860;
        server_name localhost;

        root /var/www/public;
        index index.php index.html;

        charset utf-8;

        # 1. Route utama untuk aplikasi Laravel
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # 2. Khusus menangani file gambar/statis di folder storage via alias (Biar gak 403)
        location /storage/ {
            alias /var/www/storage/app/public/;
            try_files $uri =404;
            access_log off;
            log_not_found off;
            expires max;
        }

        error_page 404 /index.php;

        # 3. Meneruskan request file PHP ke PHP-FPM
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # 4. Melindungi file tersembunyi seperti .htaccess atau .env
        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}